version: '3.4'

services:
  gameusers:
    image: gameusers:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "GameUsers"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_gameusers$
    volumes:
      - C:\Users\paj77\source\repos\GameUsers\GameUsers:/app
      - C:\Users\paj77\source\repos\GameUsers:/src
      - C:\Users\paj77\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_gameusers$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_gameusers$ \"bin\\Debug\\netcoreapp2.2\\GameUsers.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true